# Generated by Django 3.0.5 on 2020-06-11 09:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=200)),
                ('isbnNo', models.CharField(max_length=13)),
                ('authorName', models.CharField(max_length=30)),
                ('pubName', models.CharField(max_length=30)),
                ('originalPrice', models.IntegerField()),
                ('price', models.IntegerField()),
                ('edition', models.CharField(max_length=10)),
                ('bookCatgName', models.CharField(default='', max_length=200)),
                ('postedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'postedDate',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('studName', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('password', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('contactNo', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='Student')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedBook',
            fields=[
                ('purid', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('isbnNo', models.CharField(max_length=13)),
                ('studId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksharingapi.Stud')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='Book')),
                ('bookId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Book_Image', to='booksharingapi.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='booksharingapi.Stud'),
        ),
    ]
