# Generated by Django 3.0.5 on 2020-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksharingapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.CharField(max_length=30),
        ),
    ]
