version: '3'

services: 
    web:
        build: .
        command: python src/manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        depends_on: 
            - db
    db:
        image: postgres
        # restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: postgres